import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Search, ShieldCheck } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  cryptoRedditFixture,
  filterCryptoRedditPosts,
  paginateCryptoRedditPosts,
} from "@/lib/cryptoRedditFeed";

/**
 * Harvested from skylerblue333/ShadowChat-Core:
 * client/src/pages/generated/Cryptoredditfeed_168.tsx
 *
 * The source screen used loose tRPC stubs and was explicitly marked as an
 * autogenerated draft. This canonical version keeps the useful UX while
 * removing ts-nocheck, proxy stubs, and fake backend mutations.
 */
export default function CryptoRedditFeed() {
  const [searchTerm, setSearchTerm] = useState("");
  const [page, setPage] = useState(1);

  const filteredPosts = useMemo(
    () => filterCryptoRedditPosts(cryptoRedditFixture, searchTerm),
    [searchTerm]
  );
  const paginated = useMemo(
    () => paginateCryptoRedditPosts(filteredPosts, page, 10),
    [filteredPosts, page]
  );

  const updateSearch = (value: string) => {
    setSearchTerm(value);
    setPage(1);
  };

  return (
    <main
      className="min-h-screen bg-background px-4 py-8 text-foreground sm:px-6 lg:px-8"
      aria-labelledby="crypto-reddit-feed-title"
    >
      <div className="mx-auto max-w-7xl space-y-6">
        <header className="rounded-2xl border border-border/70 bg-card/80 p-6 shadow-sm sm:p-8">
          <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
            <div className="space-y-3">
              <div className="flex flex-wrap items-center gap-2">
                <Badge variant="outline">ShadowChat-Core harvest</Badge>
                <Badge variant="secondary">Local verified fixture</Badge>
              </div>
              <div>
                <h1
                  id="crypto-reddit-feed-title"
                  className="text-3xl font-semibold tracking-tight sm:text-4xl"
                >
                  Crypto Reddit Feed
                </h1>
                <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground sm:text-base">
                  Canonicalized from the distinct ShadowChat-Core screen while
                  preserving truthful data boundaries. Live external feed access
                  remains disabled until a verified backend contract is available.
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <ShieldCheck className="size-4 text-primary" aria-hidden="true" />
              Typed • searchable • paginated
            </div>
          </div>
        </header>

        <Card>
          <CardHeader>
            <CardTitle>Community feed</CardTitle>
            <CardDescription>
              Search and pagination are fully functional locally. No fake network
              request or fabricated live status is used.
            </CardDescription>
            <div className="relative max-w-xl pt-2">
              <Search
                className="pointer-events-none absolute left-3 top-4 size-4 text-muted-foreground"
                aria-hidden="true"
              />
              <Input
                aria-label="Search crypto Reddit posts"
                placeholder="Search posts or authors..."
                value={searchTerm}
                onChange={event => updateSearch(event.target.value)}
                className="pl-9"
              />
            </div>
          </CardHeader>
          <CardContent className="space-y-6">
            {paginated.items.length > 0 ? (
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                {paginated.items.map(post => (
                  <article
                    key={post.id}
                    className="rounded-xl border border-border/70 bg-card p-5 transition-shadow hover:shadow-md"
                  >
                    <h2 className="line-clamp-3 text-lg font-semibold leading-tight">
                      {post.title}
                    </h2>
                    <dl className="mt-4 space-y-2 text-sm text-muted-foreground">
                      <div className="flex justify-between gap-3">
                        <dt>Author</dt>
                        <dd className="font-medium text-foreground">{post.author}</dd>
                      </div>
                      <div className="flex justify-between gap-3">
                        <dt>Score</dt>
                        <dd className="font-medium text-foreground">{post.score}</dd>
                      </div>
                      <div className="flex justify-between gap-3">
                        <dt>Provenance</dt>
                        <dd className="font-medium text-foreground">ShadowChat-Core</dd>
                      </div>
                    </dl>
                  </article>
                ))}
              </div>
            ) : (
              <div
                className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground"
                role="status"
              >
                No posts match “{searchTerm}”.
              </div>
            )}

            <nav className="flex items-center justify-center gap-3" aria-label="Feed pagination">
              <Button
                type="button"
                variant="outline"
                size="icon"
                onClick={() => setPage(current => Math.max(1, current - 1))}
                disabled={paginated.page === 1}
                aria-label="Previous page"
              >
                <ChevronLeft className="size-4" />
              </Button>
              <span className="min-w-24 text-center text-sm font-medium">
                Page {paginated.page} of {paginated.totalPages}
              </span>
              <Button
                type="button"
                variant="outline"
                size="icon"
                onClick={() =>
                  setPage(current => Math.min(paginated.totalPages, current + 1))
                }
                disabled={paginated.page === paginated.totalPages}
                aria-label="Next page"
              >
                <ChevronRight className="size-4" />
              </Button>
            </nav>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
