import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Compass, Filter, Flag, Layers3, LockKeyhole, Map, RefreshCw, Search, ShieldCheck, Sparkles, TriangleAlert, WifiOff } from "lucide-react";
import { ScreenFeatureGrid, ScreenHero, ScreenPreviewBanner, ScreenStatGrid } from "@/components/ScreenExperience";

type Group = "Core" | "Finance" | "AI" | "Education" | "Community";
type Status = "Verified preview" | "Needs evidence" | "Unavailable";
type Feature = { id: string; label: string; group: Group; description: string; rarity: "Core" | "Featured" | "Exploratory"; status: Status; route: string };
const features: Feature[] = [
  { id: "dashboard", label: "Ecosystem Dashboard", group: "Core", description: "Cross-module navigation and status overview.", rarity: "Core", status: "Verified preview", route: "/dashboard" },
  { id: "profiles", label: "Profiles and Settings", group: "Core", description: "Account surface concepts with local settings boundaries.", rarity: "Core", status: "Needs evidence", route: "/settings" },
  { id: "wallet", label: "Wallet Concepts", group: "Finance", description: "Wallet, portfolio, and custody surfaces requiring chain proof.", rarity: "Featured", status: "Needs evidence", route: "/wallet" },
  { id: "exchange", label: "Exchange Concepts", group: "Finance", description: "Market and order surfaces with provider requirements.", rarity: "Featured", status: "Needs evidence", route: "/exchange" },
  { id: "hope", label: "HopeAI", group: "AI", description: "AI interaction surfaces requiring model and safety evidence.", rarity: "Featured", status: "Needs evidence", route: "/hope-ai" },
  { id: "marketplace", label: "AI Marketplace", group: "AI", description: "Tool and capability discovery concepts.", rarity: "Exploratory", status: "Needs evidence", route: "/ai-marketplace" },
  { id: "school", label: "SkySchool", group: "Education", description: "Courses, quizzes, progress, and certification concepts.", rarity: "Featured", status: "Needs evidence", route: "/sky-school" },
  { id: "community", label: "Community Hub", group: "Community", description: "Community, moderation, and participation concepts.", rarity: "Exploratory", status: "Needs evidence", route: "/community" },
  { id: "notifications", label: "Notifications", group: "Core", description: "Notification preferences and delivery states.", rarity: "Core", status: "Verified preview", route: "/notifications" },
];
const groups: Group[] = ["Core", "Finance", "AI", "Education", "Community"];
const statuses: Array<Status | "All"> = ["All", "Verified preview", "Needs evidence", "Unavailable"];
export default function PlatformMap() {
  const [group, setGroup] = useState<Group | "All">("All");
  const [status, setStatus] = useState<Status | "All">("All");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(features[0]);
  const [saved, setSaved] = useState(false);
  const filtered = useMemo(() => features.filter((item) => {
    const text = `${item.label} ${item.description} ${item.route}`.toLowerCase();
    return (group === "All" || item.group === group) && (status === "All" || item.status === status) && (!query || text.includes(query.toLowerCase()));
  }), [group, query, status]);
  const reset = () => { setGroup("All"); setStatus("All"); setQuery(""); setSelected(features[0]); setSaved(false); };
  return (
    <div className="min-h-screen bg-[#070a16] text-white">
      <ScreenHero icon={Map} eyebrow="PlatformMap · Ecosystem index" title="Explore the ecosystem without labeling every route live." description="Search grouped feature concepts, review implementation-state labels, and inspect route boundaries. This index is a navigation aid; it does not certify functionality, backend readiness, data freshness, security, or production availability." badge="Ecosystem preview">
        <div className="flex flex-wrap gap-2"><Button disabled={filtered.length === 0} onClick={() => setSaved(true)} className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Flag className="mr-2 size-4" />{saved ? "Map view saved locally" : "Save map view"}</Button><Button onClick={reset} variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10"><RefreshCw className="mr-2 size-4" />Reset map</Button></div>
      </ScreenHero>
      <main className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6 lg:px-8">
        <ScreenStatGrid items={[{ label: "Route concepts", value: String(features.length), hint: "Local index", icon: Layers3, tone: "cyan" }, { label: "Groups", value: String(groups.length), hint: "Ecosystem areas", icon: Compass, tone: "violet" }, { label: "Visible", value: String(filtered.length), hint: "Local filters", icon: Filter, tone: "amber" }, { label: "Source", value: "Off", hint: "No availability probe", icon: WifiOff, tone: "slate" }]} />
        <ScreenPreviewBanner title="Platform map evidence boundary"><strong>This is not a live feature registry or completeness certificate.</strong> Labels such as core, featured, exploratory, verified preview, needs evidence, and unavailable are local navigation metadata. They do not prove a route renders, a backend works, a connector is active, a user can transact, or a feature is production-ready.</ScreenPreviewBanner>
        <section className="grid gap-6 lg:grid-cols-[0.82fr_1fr]">
          <Card className="border-white/10 bg-white/[0.04]"><CardContent className="p-6"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search route concepts…" className="w-full rounded-xl border border-white/10 bg-black/20 py-3 pl-9 pr-3 text-sm text-white outline-none focus:border-cyan-300/50" /></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Ecosystem groups</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => setGroup("All")} className={`rounded-lg border px-3 py-2 text-xs ${group === "All" ? "border-cyan-300/40 bg-cyan-300/10 text-cyan-200" : "border-white/10 text-slate-500"}`}>All</button>{groups.map((item) => <button key={item} onClick={() => setGroup(item)} className={`rounded-lg border px-3 py-2 text-xs ${group === item ? "border-cyan-300/40 bg-cyan-300/10 text-cyan-200" : "border-white/10 text-slate-500"}`}>{item}</button>)}</div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.2em] text-amber-200">Implementation state</p><div className="mt-3 grid gap-2">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={`flex items-center justify-between rounded-xl border p-3 text-left ${status === item ? "border-cyan-300/40 bg-cyan-300/[0.06]" : "border-white/10 text-slate-400"}`}><span className="text-sm font-semibold">{item}</span><span className="text-xs text-slate-500">{item === "All" ? features.length : features.filter((feature) => feature.status === item).length}</span></button>)}</div><div className="mt-6 rounded-xl border border-amber-300/20 bg-amber-300/[0.06] p-4"><div className="flex gap-3"><TriangleAlert className="mt-0.5 size-5 shrink-0 text-amber-200" /><p className="text-sm leading-6 text-slate-300">Use each route's evidence record and useful-state screenshot to determine actual readiness. The map should never overrule route-level proof.</p></div></div></CardContent></Card>
          <Card className="border-white/10 bg-white/[0.04]"><CardContent className="p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-200">Feature concepts</p><h2 className="mt-2 text-2xl font-black">{group === "All" ? "All ecosystem areas" : group}</h2></div><Badge variant="outline" className="border-white/10 text-amber-200">{filtered.length} visible</Badge></div><div className="mt-5 space-y-3">{filtered.length === 0 ? <div className="rounded-xl border border-dashed border-white/15 p-8 text-center"><p className="font-semibold">No concepts match</p><p className="mt-2 text-sm text-slate-500">Change the local filters.</p></div> : filtered.map((item) => <button key={item.id} onClick={() => setSelected(item)} className={`w-full rounded-xl border p-4 text-left ${selected.id === item.id ? "border-cyan-300/40 bg-cyan-300/[0.06]" : "border-white/10"}`}><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-cyan-300/10"><Sparkles className="size-4 text-cyan-200" /></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.label}</p><Badge variant="outline" className="border-white/10 text-slate-400">{item.group}</Badge><Badge variant="outline" className="border-white/10 text-amber-200">{item.rarity}</Badge></div><p className="mt-1 text-sm text-slate-500">{item.description}</p></div><span className="text-xs text-slate-500">{item.status}</span></div></button>)}</div><div className="mt-5 rounded-xl border border-white/10 p-4"><p className="text-xs text-slate-500">Selected route concept</p><p className="mt-2 text-lg font-black">{selected.label}</p><p className="mt-2 text-sm leading-6 text-slate-400">{selected.description}</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{[{ label: "Route", value: selected.route }, { label: "State", value: selected.status }, { label: "Source", value: "Unavailable" }].map((item) => <div key={item.label} className="rounded-xl border border-white/10 p-3"><p className="text-xs text-slate-500">{item.label}</p><p className="mt-2 text-sm font-semibold text-amber-200">{item.value}</p></div>)}</div></div></CardContent></Card>
        </section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.8fr]"><Card className="border-white/10 bg-white/[0.04]"><CardContent className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-200">Map governance</p><h2 className="mt-2 text-2xl font-black">The index must prove</h2><div className="mt-5 space-y-3">{["Route registry generated from source with owner, version, status, and last-verified timestamp", "Browser and API contract checks for every route, including loading/error/empty/accessibility states", "Evidence ledger linking claims to implementation, tests, connectors, environment, and screenshots", "No sensitive routes, credentials, secrets, internal URLs, or unsupported availability claims exposed", "Change review, rollback, stale-entry cleanup, and automated drift detection"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><ShieldCheck className="size-4 text-slate-500" /><span className="flex-1 text-sm text-slate-300">{item}</span><span className="text-xs text-amber-200">Required</span></div>)}</div></CardContent></Card><Card className="border-white/10 bg-white/[0.04]"><CardContent className="p-6"><LockKeyhole className="size-5 text-cyan-300" /><h2 className="mt-4 text-xl font-black">No fake completeness</h2><p className="mt-3 text-sm leading-6 text-slate-400">Filtering or saving a map view changes local state only. It does not certify routes, activate connectors, verify users, prove live data, or declare the platform production-ready.</p></CardContent></Card></section>
        <ScreenFeatureGrid features={[{ title: "Five ecosystem groups preserved", description: "Core, Finance, AI, Education, and Community concepts remain searchable and filterable.", icon: Layers3, status: "Local index" }, { title: "Implementation state is visible", description: "Verified preview, needs evidence, and unavailable labels prevent blanket live claims.", icon: ShieldCheck, status: "Guardrail" }, { title: "Availability probes are off", description: "No route, connector, data source, transaction, or production readiness is fabricated.", icon: WifiOff, status: "Unavailable" }]} />
      </main>
    </div>
  );
}
